name: Create a PR from dev to main and auto-merge

on:
  push:
    branches:
      - dev

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Create or update Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync dev to main"
          title: "Auto PR: dev → main"
          body: "Automated PR from dev branch to main branch"
          base: main

      - name: Merge Pull Request
        if: steps.cpr.outputs.pull-request-number != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = parseInt("${{ steps.cpr.outputs.pull-request-number }}");
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: "merge"
            });
